# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x1a\x1bgoogle/protobuf/empty.proto\">\n\x07\x43ontact\x12\x11\n\thome_addr\x18\x01 \x01(\t\x12\x0f\n\x07mob_num\x18\x02 \x01(\t\x12\x0f\n\x07mail_id\x18\x03 \x01(\t\"f\n\x08\x45mployee\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x19\n\x07\x63ontact\x18\x05 \x01(\x0b\x32\x08.Contact\"\x18\n\nEmployeeID\x12\n\n\x02id\x18\x01 \x01(\t2\x84\x02\n\x12\x45mployeeManagement\x12%\n\x0bgetEmployee\x12\x0b.EmployeeID\x1a\t.Employee\x12\x34\n\rlistEmployees\x12\x16.google.protobuf.Empty\x1a\t.Employee0\x01\x12%\n\x0bsetEmployee\x12\t.Employee\x1a\x0b.EmployeeID\x12\x33\n\x0eupdateEmployee\x12\t.Employee\x1a\x16.google.protobuf.Empty\x12\x35\n\x0e\x64\x65leteEmployee\x12\x0b.EmployeeID\x1a\x16.google.protobuf.EmptyB\x0bZ\tproto/empb\x06proto3')



_CONTACT = DESCRIPTOR.message_types_by_name['Contact']
_EMPLOYEE = DESCRIPTOR.message_types_by_name['Employee']
_EMPLOYEEID = DESCRIPTOR.message_types_by_name['EmployeeID']
Contact = _reflection.GeneratedProtocolMessageType('Contact', (_message.Message,), {
  'DESCRIPTOR' : _CONTACT,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:Contact)
  })
_sym_db.RegisterMessage(Contact)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEE,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:Employee)
  })
_sym_db.RegisterMessage(Employee)

EmployeeID = _reflection.GeneratedProtocolMessageType('EmployeeID', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEEID,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:EmployeeID)
  })
_sym_db.RegisterMessage(EmployeeID)

_EMPLOYEEMANAGEMENT = DESCRIPTOR.services_by_name['EmployeeManagement']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\tproto/emp'
  _CONTACT._serialized_start=47
  _CONTACT._serialized_end=109
  _EMPLOYEE._serialized_start=111
  _EMPLOYEE._serialized_end=213
  _EMPLOYEEID._serialized_start=215
  _EMPLOYEEID._serialized_end=239
  _EMPLOYEEMANAGEMENT._serialized_start=242
  _EMPLOYEEMANAGEMENT._serialized_end=502
# @@protoc_insertion_point(module_scope)
